chore(LT-5856): [Lykke.Service.FakeExchangeConnector] Update MessageP…
LykkeBusiness/Lykke.Service.FakeExchangeConnector pull request #18
Opened 2024-10-28 10:29 UTC by lykke-vashetsin

…ack to 2.x version

2024-11-05 13:42 UTC, tarurar requested changes

2024-11-05 13:42 UTC, tarurar commented on Directory.Packages.props
> +    <PackageVersion Include="MessagePack" Version="2.5.187" />
You probably do not need direct dependency on MessagePack.

2024-11-05 19:41 UTC, lykke-vashetsin commented on Directory.Packages.props
> +    <PackageVersion Include="MessagePack" Version="2.5.187" />
I tried, didn't work

2024-11-11 08:07 UTC, tarurar approved these changes

2024-11-11 08:34 UTC, merged